/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Colour.Profiler;
import Exception.InputErrorExceptions;
import Network.NeuralNetwork;
import Persister.FileHandler;
import Persister.Persister;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yashu
 */
public class Project3GUI extends javax.swing.JFrame {

	NeuralNetwork nn;
	double learningRate = 0.9;
	double momentum = 0.4;
	int numEp = 1000;
	int numDivisions = 3;;
	double thresh = 0.7;
	double smooth = 1;
	int numLayers = 1;
	int numHidden = 5;
	int numRepeat = 1;
	Persister settings;
	
	
	/**
	 * Creates new form Project3GUI
	 */
	public Project3GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

                fileChooser = new javax.swing.JFileChooser();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                LearnRate = new javax.swing.JSlider();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                momentumRate = new javax.swing.JSlider();
                jLabel4 = new javax.swing.JLabel();
                numEpochs = new javax.swing.JSlider();
                jLabel5 = new javax.swing.JLabel();
                threshold = new javax.swing.JSlider();
                jLabel6 = new javax.swing.JLabel();
                smoothness = new javax.swing.JSlider();
                btnTeach = new javax.swing.JButton();
                btnClassify = new javax.swing.JButton();
                editLearningRate = new javax.swing.JTextField();
                editMomentumRate = new javax.swing.JTextField();
                editEpochs = new javax.swing.JTextField();
                eidtThreshold = new javax.swing.JTextField();
                editSmoothness = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                numDiv = new javax.swing.JSlider();
                jTextField1 = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                numLay = new javax.swing.JSlider();
                jTextField2 = new javax.swing.JTextField();
                compl = new javax.swing.JToggleButton();
                btnSettings = new javax.swing.JButton();
                jLabel9 = new javax.swing.JLabel();
                numH = new javax.swing.JSlider();
                jTextField3 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                repeat = new javax.swing.JSlider();
                jTextField4 = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
                jLabel1.setText("COS 314_ Project_3_Neural_Network");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1)
                                .addContainerGap(123, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                LearnRate.setMajorTickSpacing(50);
                LearnRate.setMinorTickSpacing(10);
                LearnRate.setPaintLabels(true);
                LearnRate.setPaintTicks(true);
                LearnRate.setToolTipText("Learn Rate");
                LearnRate.setValue(90);
                LearnRate.setName("learnRate"); // NOI18N
                LearnRate.setValueIsAdjusting(true);

                jLabel2.setText("Learning Rate /100");

                jLabel3.setText("Momentum /100");

                momentumRate.setMajorTickSpacing(50);
                momentumRate.setMinorTickSpacing(10);
                momentumRate.setPaintLabels(true);
                momentumRate.setPaintTicks(true);
                momentumRate.setToolTipText("Momentum");
                momentumRate.setValue(40);

                jLabel4.setText("Epochs");

                numEpochs.setMajorTickSpacing(50);
                numEpochs.setMaximum(1000);
                numEpochs.setMinimum(50);
                numEpochs.setMinorTickSpacing(10);
                numEpochs.setPaintTicks(true);
                numEpochs.setValue(1000);

                jLabel5.setText("Threshold/100");

                threshold.setMajorTickSpacing(50);
                threshold.setMinorTickSpacing(10);
                threshold.setPaintLabels(true);
                threshold.setPaintTicks(true);
                threshold.setValue(70);

                jLabel6.setText("Smoothness/100");

                smoothness.setMajorTickSpacing(50);
                smoothness.setMinorTickSpacing(10);
                smoothness.setPaintLabels(true);
                smoothness.setPaintTicks(true);
                smoothness.setValue(100);

                btnTeach.setText("Teach, Test and Generate Data");
                btnTeach.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTeachActionPerformed(evt);
                        }
                });

                btnClassify.setText("classify image");
                btnClassify.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClassifyActionPerformed(evt);
                        }
                });

                editLearningRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, LearnRate, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), editLearningRate, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                editMomentumRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, momentumRate, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), editMomentumRate, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                editEpochs.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, numEpochs, org.jdesktop.beansbinding.ELProperty.create("${value}"), editEpochs, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                eidtThreshold.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, threshold, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), eidtThreshold, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                editSmoothness.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, smoothness, org.jdesktop.beansbinding.ELProperty.create("${value/100}"), editSmoothness, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                jLabel7.setText("Divisions");

                numDiv.setMajorTickSpacing(1);
                numDiv.setMaximum(10);
                numDiv.setMinimum(1);
                numDiv.setMinorTickSpacing(1);
                numDiv.setPaintLabels(true);
                numDiv.setPaintTicks(true);
                numDiv.setSnapToTicks(true);
                numDiv.setValue(3);

                jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, numDiv, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                jLabel8.setText("Hidden Layers");

                numLay.setMajorTickSpacing(1);
                numLay.setMaximum(10);
                numLay.setMinimum(1);
                numLay.setMinorTickSpacing(1);
                numLay.setPaintLabels(true);
                numLay.setPaintTicks(true);
                numLay.setSnapToTicks(true);
                numLay.setValue(2);

                jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, numLay, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                compl.setSelected(true);
                compl.setText("Theta sigmoid calculation");
                compl.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                complActionPerformed(evt);
                        }
                });

                btnSettings.setText("Save Settings");
                btnSettings.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSettingsActionPerformed(evt);
                        }
                });

                jLabel9.setText("Hidden Nodes/ Layer");

                numH.setMajorTickSpacing(1);
                numH.setMaximum(15);
                numH.setMinimum(3);
                numH.setMinorTickSpacing(1);
                numH.setPaintLabels(true);
                numH.setPaintTicks(true);
                numH.setSnapToTicks(true);
                numH.setValue(5);

                jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, numH, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                jLabel10.setText("Iterations(Test)");

                repeat.setMajorTickSpacing(15);
                repeat.setMaximum(30);
                repeat.setMinimum(1);
                repeat.setMinorTickSpacing(1);
                repeat.setPaintTicks(true);
                repeat.setSnapToTicks(true);

                jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, repeat, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField4, org.jdesktop.beansbinding.BeanProperty.create("text"));
                bindingGroup.addBinding(binding);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(momentumRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(LearnRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGap(137, 137, 137))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(numEpochs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGap(54, 54, 54)))
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(editLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(editEpochs, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(editMomentumRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(110, 110, 110)
                                                                                .addComponent(threshold, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel5)
                                                                                        .addComponent(jLabel6))
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(smoothness, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(57, 57, 57)
                                                                .addComponent(editSmoothness, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(eidtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(196, 196, 196)
                                                .addComponent(compl)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnTeach)
                                                .addGap(42, 42, 42)
                                                .addComponent(btnSettings)
                                                .addGap(37, 37, 37)
                                                .addComponent(btnClassify, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(12, 12, 12)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(jLabel8)))
                                                                        .addComponent(jLabel9))
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(7, 7, 7)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(numLay, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(numDiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(repeat, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                                                        .addComponent(numH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                        .addComponent(jLabel10))
                                                .addGap(54, 54, 54)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LearnRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(editLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(momentumRate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editMomentumRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(editEpochs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numEpochs, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(threshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eidtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(smoothness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(compl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(editSmoothness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numLay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(numH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(repeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnTeach)
                                        .addComponent(btnSettings)
                                        .addComponent(btnClassify))
                                .addGap(29, 29, 29))
                );

                momentumRate.getAccessibleContext().setAccessibleName("momentum");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                );

                bindingGroup.bind();

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachActionPerformed
                learningRate = (double)LearnRate.getValue()/100;
		momentum = (double)momentumRate.getValue()/100;
		numEp = numEpochs.getValue();
		thresh = (double)threshold.getValue()/100;
		smooth = smoothness.getValue()/100;
		numDivisions = numDiv.getValue();
		numLayers = numLay.getValue();
		Profiler profiler = new Profiler(numDivisions);
		numHidden = numH.getValue();
		numRepeat = repeat.getValue();
		FileHandler filehandlerTeach;
		FileHandler filehandlerGeneral;
		try 
		{
			filehandlerTeach = new FileHandler("images.txt");
			filehandlerGeneral = new FileHandler("imagesGeneral.txt");
			String[] Trecords = filehandlerTeach.getRecords();
			boolean[] Tclassifications = filehandlerTeach.getClasses();
			String[] Grecords = filehandlerGeneral.getRecords();
			double[][] inputs = new double[Trecords.length][profiler.getNumBuckets()];
			for (int i = 0; i < Trecords.length; i++) 
			{
				inputs[i] = profiler.profile(Trecords[i]);
				//System.out.println("added something to input");
				//System.out.println("inputs["+i+"]: " + inputs[i]);
			}
			double[][] generalInputs = new double[Trecords.length][profiler.getNumBuckets()];
			for (int i = 0; i < Grecords.length; i++) 
			{
				generalInputs[i] = profiler.profile(Grecords[i]);
				//System.out.println("added something to general");
			}
			thresh = Profiler.normalize((double)thresh, (double)((-1) * (1 /Math.sqrt(profiler.getNumBuckets()))), (double)(1 / Math.sqrt(profiler.getNumBuckets())), 0, 1);
			nn = new NeuralNetwork(inputs, Tclassifications, learningRate, momentum, numEp, thresh, smooth, generalInputs, numLayers, numHidden);
			nn.teach(numRepeat);
			System.out.println("done :)");
		} 
		catch (IOException | InputErrorExceptions ex) 
		{
			Logger.getLogger(Project3GUI.class.getName()).log(Level.SEVERE, null, ex);
		}
        }//GEN-LAST:event_btnTeachActionPerformed

        private void btnClassifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassifyActionPerformed
                int chosen = fileChooser.showOpenDialog(jLabel1);
		if (chosen == javax.swing.JFileChooser.APPROVE_OPTION) 
		{
			java.io.File file = fileChooser.getSelectedFile();
			String filename = file.getAbsolutePath();
			Profiler p = new Profiler(numDivisions);
			String classification = nn.classifySingleImage(p.profile(filename));
			JOptionPane.showMessageDialog(this.btnClassify,classification);
			System.out.println("done :)");
		}
		
        }//GEN-LAST:event_btnClassifyActionPerformed

        private void complActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complActionPerformed
                boolean isSelected = compl.isSelected();
		threshold.setEnabled(isSelected);
		smoothness.setEnabled(isSelected);
		nn.switchComplicated();
        }//GEN-LAST:event_complActionPerformed

        private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
                settings = new Persister("settings.txt");
		settings.write("learningRate:" + learningRate);
		settings.flush();
		settings.write("\nmomentum:" + momentum);
		settings.flush();
		settings.write("\nnumEp:" + numEp);
		settings.flush();
		settings.write("\nnumDivisions:" + numDivisions);
		settings.flush();
		settings.write("\nsmooth:" + smooth);
		settings.flush();
		settings.write("\nnumLayers:" + numLayers);
		settings.flush();
		settings.write("\nnumHidden" + numHidden+"\n");
		settings.close();
        }//GEN-LAST:event_btnSettingsActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Project3GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Project3GUI().setVisible(true);
			}
		});
	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JSlider LearnRate;
        private javax.swing.JButton btnClassify;
        private javax.swing.JButton btnSettings;
        private javax.swing.JButton btnTeach;
        private javax.swing.JToggleButton compl;
        private javax.swing.JTextField editEpochs;
        private javax.swing.JTextField editLearningRate;
        private javax.swing.JTextField editMomentumRate;
        private javax.swing.JTextField editSmoothness;
        private javax.swing.JTextField eidtThreshold;
        private javax.swing.JFileChooser fileChooser;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JSlider momentumRate;
        private javax.swing.JSlider numDiv;
        private javax.swing.JSlider numEpochs;
        private javax.swing.JSlider numH;
        private javax.swing.JSlider numLay;
        private javax.swing.JSlider repeat;
        private javax.swing.JSlider smoothness;
        private javax.swing.JSlider threshold;
        private org.jdesktop.beansbinding.BindingGroup bindingGroup;
        // End of variables declaration//GEN-END:variables
}
